// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_l2H-CePhIQ78FRNGYV5jYHM5f24VNCo',
    appId: '1:688143166946:web:47db229a5202e728525dbb',
    messagingSenderId: '688143166946',
    projectId: 'go-school-pms',
    authDomain: 'go-school-pms.firebaseapp.com',
    storageBucket: 'go-school-pms.appspot.com',
    measurementId: 'G-HCFFGB29BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkdKeQJbcTN6ZsgwFp31yM9i7UVkDRlw',
    appId: '1:688143166946:android:2aaddf9f1f5887de525dbb',
    messagingSenderId: '688143166946',
    projectId: 'go-school-pms',
    storageBucket: 'go-school-pms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsfPco8u-sxunDjGvbyY8gIRTFI3xnxGA',
    appId: '1:688143166946:ios:aff390c30db2a14c525dbb',
    messagingSenderId: '688143166946',
    projectId: 'go-school-pms',
    storageBucket: 'go-school-pms.appspot.com',
    iosBundleId: 'com.example.goSchoolApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsfPco8u-sxunDjGvbyY8gIRTFI3xnxGA',
    appId: '1:688143166946:ios:aff390c30db2a14c525dbb',
    messagingSenderId: '688143166946',
    projectId: 'go-school-pms',
    storageBucket: 'go-school-pms.appspot.com',
    iosBundleId: 'com.example.goSchoolApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_l2H-CePhIQ78FRNGYV5jYHM5f24VNCo',
    appId: '1:688143166946:web:6cec19419c34bdc0525dbb',
    messagingSenderId: '688143166946',
    projectId: 'go-school-pms',
    authDomain: 'go-school-pms.firebaseapp.com',
    storageBucket: 'go-school-pms.appspot.com',
    measurementId: 'G-VT0JX625CP',
  );
}
